/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[404]': RouteRecordInfo<'/[404]', '/:404', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/logout': RouteRecordInfo<'/auth/logout', '/auth/logout', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/RoomofTopic/[TopicId]': RouteRecordInfo<'/RoomofTopic/[TopicId]', '/RoomofTopic/:TopicId', { TopicId: ParamValue<true> }, { TopicId: ParamValue<false> }>,
    '/rooms/[RoomId]': RouteRecordInfo<'/rooms/[RoomId]', '/rooms/:RoomId', { RoomId: ParamValue<true> }, { RoomId: ParamValue<false> }>,
    '/topic/': RouteRecordInfo<'/topic/', '/topic', Record<never, never>, Record<never, never>>,
    '/topic/create': RouteRecordInfo<'/topic/create', '/topic/create', Record<never, never>, Record<never, never>>,
    '/trend/': RouteRecordInfo<'/trend/', '/trend', Record<never, never>, Record<never, never>>,
  }
}
